apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx-deployment
spec:
  strategy:
    type:
  replicas: 5
  selector:
    matchLabels:
      app: my-nginx-pod
  template:
    metadata:
      labels:
        app: my-nginx-pod
    spec:
      containers:
        - name: nginx
          image: nginx:1.25.0
          ports:
            - containerPort: 80