apiVersion: v1
kind: Pod
metadata:
  name: my-web
  labels:
    app: web
    version: v1
    type: application
spec:
  containers:
    - name: my-application
      image: busybox
      args: ["tail","-f","/dev/null"]

---

apiVersion: v1
kind: Pod
metadata:
  name: my-web2
  labels:
    app: web
    version: v2
    type: application
spec:
  containers:
    - name: my-application
      image: busybox
      args: ["tail","-f","/dev/null"]

---

apiVersion: v1
kind: Pod
metadata:
  name: my-server
  labels:
    app: server
    version: v1
    type: infra
spec:
  containers:
    - name: my-application
      image: busybox
      args: ["tail","-f","/dev/null"]

---

apiVersion: v1
kind: Pod
metadata:
  name: my-db
  labels:
    app: db
    version: v1
    type: infra
spec:
  containers:
    - name: my-application
      image: busybox
      args: ["tail","-f","/dev/null"]